# Generated by Django 6.0.7 on 2026-07-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Learning', 'Learning'), ('Project', 'Project'), ('Reading', 'Reading'), ('Code', 'Code'), ('Exercises', 'Exercises'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], default='moyenne', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('à faire', 'À faire'), ('en cours', 'En cours'), ('terminé', 'Terminé')], default='à faire', max_length=20),
        ),
    ]
