# Generated by Django 6.0.7 on 2026-07-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningprofile',
            name='career_goal',
        ),
        migrations.RemoveField(
            model_name='learningprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='learningprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='learningprofile',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='learningprofile',
            name='weekly_hours',
        ),
        migrations.AddField(
            model_name='learningprofile',
            name='career',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='learningprofile',
            name='disponibilite',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningprofile',
            name='domain',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningprofile',
            name='langue',
            field=models.CharField(default='French', max_length=20),
        ),
        migrations.AddField(
            model_name='learningprofile',
            name='niveau',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
