# Generated by Django 6.0.7 on 2026-07-12 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.JSONField(default=list)),
                ('modules', models.JSONField(default=list)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('learning_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='users.learningprofile')),
            ],
        ),
    ]
